name: smartcart
services:
  frontend:
    image: ${FRONTEND_IMAGE}
    build:
      context: ../SmartCart-Frontend
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: on-failure
    networks:
      - frontend-net

  backend:
    image: ${BACKEND_IMAGE}
    build:
      context: .
    container_name: SmartCart
    ports:
      - "8081:8081"
    environment:
      - GUNICORN=true
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=${MONGO_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - database
    restart: on-failure
    networks:
    - frontend-net
    - backend-net

  database:
    image: mongo:8.2
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    restart: on-failure
    networks:
    - backend-net

volumes:
  mongodb_data:

networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge