name: smartcart
services:
  nginx:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - smartcart
    restart: on-failure
    networks:
      - frontend-net

  smartcart:
    image: ${BACKEND_IMAGE}
    build:
      context: ..
    ports:
      - "8081:8081" # /metrics port
    environment:
      - GUNICORN=true
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=${MONGO_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongodb
    restart: on-failure
    networks:
    - frontend-net
    - backend-net

  mongodb:
    image: mongo:8.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    restart: on-failure
    networks:
    - backend-net

volumes:
  mongodb_data:

networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge